name: Unit Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'
    branches:
      - main

concurrency:
  group: unit-tests
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run Acceptance Tests
        env:
          USERNAME: ${{ secrets.STAGING_NEXAA_CLOUD_USER }}
          PASSWORD: ${{ secrets.STAGING_NEXAA_CLOUD_PASSWORD }}
          TILAA_ENV: ${{ secrets.TILAA_ENV }}
        working-directory: .
        run: go test -v -cover ./internal/resources/...
