name: Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'docs/**'

concurrency:
  group: unit-tests
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Run Unit Tests
        env:
          USERNAME: ${{ secrets.STAGING_NEXAA_CLOUD_USER }}
          PASSWORD: ${{ secrets.STAGING_NEXAA_CLOUD_PASSWORD }}
          TILAA_ENV: ${{ secrets.TILAA_ENV }}
          NEXAA_KEYCLOAK_URL: ${{ secrets.NEXAA_KEYCLOAK_URL }}
          NEXAA_GRAPHQL_URL: ${{ secrets.NEXAA_GRAPHQL_URL }}
        working-directory: .
        run: go test -v -coverprofile=coverage.out -covermode=atomic -coverpkg=./internal/... ./internal/resources/...

      - name: Generate coverage HTML report
        run: go tool cover -html=coverage.out -o coverage.html

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: unit-coverage-report
          path: |
            coverage.out
            coverage.html
          retention-days: 30
